### ISSUE TITLE
readiness probe

### ISSUE THREAD

**Issue by sebgoa** [ianmiell/kubernetes-examples#1]
One with a nice readiness probe and one with a broken one ?

**Comment by ianmiell** [comment]
Done. Note tests TODO.
https://github.com/ianmiell/kubernetes-examples/commit/6305016650ee136141426d57a84dc692fcadf2ce

**Comment by sebgoa** [comment]
yeah, I know that one :) I was thinking a more realistic example would be nice.

**Comment by ianmiell** [comment]
Hmm, well I'd like these to be 'minimal' examples for educative purposes, but I'm not against realistic minimal examples if there's a good reason to have them...
